export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS';

export const CHANGE_MODAL_VISIBILITY ='changeModalVisiblity';

export const CHANGE_DRAWER_VISIBILITY = 'CHANGE_DRAWER_VISIBILITY';

export const SET_INDEX_OF_SWIPER_IMAGE = 'SET_INDEX_OF_SWIPER_IMAGE';

export const PLANT_CREATE = 'PLANT_CREATE';

export const USER_PROFILE_INFO_UPDATE = 'USER_INFO_UPDATE';

export const PLANT_ADD_FORM_UPDATE = 'PLANT_UPDATE';

export const PLANT_ADD_FORM_RESET = 'PLANT_ADD_FORM_RESET';

export const UPDATE_CURRENT_USER_INFO = 'UPDATE_CURRENT_USER_INFO';

export const RESET_CURRENT_USER_INFO = 'ResetCurrentUserInfo';

export const LOGIN_USER  = 'LOGINUSER';

export const LOGIN_PAGE_UPDATE = 'LOGIN_PAGE_UPDATE';

export const LOGIN_PAGE_RESET = 'LOGIN_PAGE_RESET';

export const SIGNUP_USER  = 'SIGNUP_USER';

export const SIGNUP_PAGE_UPDATE = 'SIGNUP_PAGE_UPDATE';

export const SIGNUP_PAGE_RESET = 'SIGNUP_PAGE_RESET';

export const SIGNUP_PAGE_RESET_VALIDATORS = 'SIGNUP_PAGE_RESET_VALIDATORS';

export const PLANTS_FETCH_SUCCESS = 'PLANTS_FETCH_SUCCESS';
export const  PLANTS_FETCH_FAILURE = 'PLANTS_FETCH_FAILURE';

export const MAIN_PAGE_UPDATE = 'MAIN_PAGE_UPDATE';

export const FETCH_PLANTS = 'FETCH_PLANTS';

export const ADD_NEW_PLANT = 'ADD_NEW_PLANT';

export const APP_STATE_UPDATE = 'APP_STATE_UPDATE';

export const SUBMIT_USER_INFO_UPDATE = 'SUBMIT_USER_INFO_UPDATE';

