export var plants =  [
       {
         id: 1,
         key: '1', 
        commonName: "Yasmeen",
        latinName : "Latin name",
        speciesName: " Red Baloon",
        imageUrl : "https://files.genial.guru/files/news/part_15/151455/1488205-calathea_photo_05of36-650x888-650-14397a2d42-1484644360.jpg",
        country : "UAE",
        city : "Dubai",
        price : 24,
        transactionType:'Swapping',
        size: '1 gallon',
        quantity : 3,
        age : 110,
        discription : 'Jasmine (taxonomic name Jasminum /ˈjæsmɪnəm/) is a genus of shrubs and\
         vines in the olive family (Oleaceae). It contains around 200 species native to\
        tropical and warm temperate regions of Eurasia, Australasia and Oceania.\
        Jasmines are widely cultivated for the characteristic fragrance of their flowers.',
        views:24,
        likes : 22,
        state:'Dubai',
        postal_code:'00000',
        street_address:'Doroshab', 
        // latitude: 15.715903,
        // longitude:32.561120,
         latitude: 15.715903,
        longitude:32.561120,
        formattedAddress:' 1600 Amphitheatre Pkwy. Mountain View, CA 94043',
        same_user_location : 0,
        username:'Mustafa.Alghali.11',
        userphone:'+249905705498',
        useremail:'mustafa@plantmatch.co',
        userfacebook:null,
        usergoogle:null,
        userInstagram:null,
        userphoto_uri:'http://www.maxlio.com/img/client2.jpg',
        userRating : 3.5,
        likedByCurrentUser:true,

      },
       {
         id: 2,
         key: '2', 
         commonName: "Marigolds",
        latinName : "Latin name",
        speciesName: " White",
        imageUrl : "http://cdn.home-designing.com/wp-content/uploads/2017/01/indoor-plants-Xerosicyos-danguyi-600x600.jpg",
        country : "US",
        city : "Seattle",
        price : 5,
        transactionType:'Adoption',
        size: '2 gallon',
        quantity : 5,
        age:15,
        discription : 'Jasmine (taxonomic name Jasminum /ˈjæsmɪnəm/) is a genus of shrubs and\
         vines in the olive family (Oleaceae). It contains around 200 species native to\
        tropical and warm temperate regions of Eurasia, Australasia and Oceania.\
        Jasmines are widely cultivated for the characteristic fragrance of their flowers.',
        views:115,
        likes : 100,
         state:'Dubai',
        postal_code:'00000',
        street_address:'Doroshab',
        latitude: 37.78825,
        longitude: -122.4324,
        formattedAddress:' 1600 Amphitheatre Pkwy. Mountain View, CA 94043',
        same_user_location : 0,
       username:'Mustafa.Alghali.11',
        userphone:'+249905705498',
        useremail:'mustafa@plantmatch.co',
        userfacebook:null,
        usergoogle:null,
        userInstagram:null,
        userphoto_uri:'http://www.maxlio.com/img/client2.jpg',
        userRating : 3.5,
        likedByCurrentUser:true,

        },


       {
           id: 3,   
            key: '3', 
         commonName: "Red Rose",
         latinName : "English Roses",
        speciesName: "Lovely Roses",
        imageUrl : "http://cdn.home-designing.com/wp-content/uploads/2017/01/indoor-cactus-Opuntia-microdasys-600x804.jpg",
        country : "Canada",
        city : "Toronto",
        price : 13,
        transactionType:'Swapping',
        size: '1 quart',
        quantity : 1,
        age:3,
        discription : 'Jasmine (taxonomic name Jasminum /ˈjæsmɪnəm/) is a genus of shrubs and\
         vines in the olive family (Oleaceae). It contains around 200 species native to\
        tropical and warm temperate regions of Eurasia, Australasia and Oceania.\
        Jasmines are widely cultivated for the characteristic fragrance of their flowers.',
        
        views:70,
        likes : 65,
         state:'Dubai',
        postal_code:'00000',
        street_address:'Doroshab',
        latitude: 37.78825,
        longitude: -122.4324,
        formattedAddress:' 1600 Amphitheatre Pkwy. Mountain View, CA 94043',
        same_user_location : 0,
        username:'Mustafa.Alghali.11',
        userphone:'+249905705498',
        useremail:'mustafa@plantmatch.co',
        userfacebook:null,
        usergoogle:null,
        userInstagram:null,
        userphoto_uri:'http://www.maxlio.com/img/client2.jpg',
        userRating : 3.5,
        likedByCurrentUser:true,
        }
         ,
       {
           id: 4,
            key: '4', 
         commonName: "Lovely Plant",
         latinName : "Latin name",
        speciesName: " dump sample",
        imageUrl : "https://ucrtoday.ucr.edu/wp-content/uploads/2012/03/botanic-garden-008-386x256.jpg",
        country : "UAE",
        city : "Abu Dhabi",
        price : 21,
        transactionType:'Swapping',
        size: '4 gallons',
        quantity : 31,
        age:218,
        discription : 'Jasmine (taxonomic name Jasminum /ˈjæsmɪnəm/) is a genus of shrubs and\
         vines in the olive family (Oleaceae). It contains around 200 species native to\
        tropical and warm temperate regions of Eurasia, Australasia and Oceania.\
        Jasmines are widely cultivated for the characteristic fragrance of their flowers.',
        
        views:14,
        likes : 12,
        state:'Dubai',
        postal_code:'00000',
        street_address:'Doroshab',
        latitude: 37.78825,
        longitude: -122.4324,
        formattedAddress:' 1600 Amphitheatre Pkwy. Mountain View, CA 94043',
        same_user_location : 0,
        username:'Mustafa.Alghali.11',
        userphone:'+249905705498',
        useremail:'mustafa@plantmatch.co',
        userfacebook:null,
        usergoogle:null,
        userInstagram:null,
        userphoto_uri:'http://www.maxlio.com/img/client2.jpg',
        userRating : 3.5,
        likedByCurrentUser:true,
        }
         ,
       {
          id: 5, 
           key: '5', 
        commonName: "Black and White",
        latinName : "Latin name",
        speciesName: " dump sample",
        imageUrl : "https://mgessex.files.wordpress.com/2012/03/coleus-at-mg-plant-sale-2015.jpg", 
        country : "US",
        city : "Seattle",
        price : 19,
        transactionType:'Adoption', 
        size: '1.5 gallons',
        quantity : 10,
        age:43,
        discription : 'Jasmine (taxonomic name Jasminum /ˈjæsmɪnəm/) is a genus of shrubs and\
         vines in the olive family (Oleaceae). It contains around 200 species native to\
        tropical and warm temperate regions of Eurasia, Australasia and Oceania.\
        Jasmines are widely cultivated for the characteristic fragrance of their flowers.',
        views:46,
        likes : 39,
        state:'Dubai',
        postal_code:'00000',
        street_address:'Doroshab',
        latitude: 37.78825,
        longitude: -122.4324,
        formattedAddress:' 1600 Amphitheatre Pkwy. Mountain View, CA 94043',
        same_user_location : 0,
        username:'Mustafa.Alghali.11',
        userphone:'+249905705498',
        useremail:'mustafa@plantmatch.co',
        userfacebook:null,
        usergoogle:null,
        userInstagram:null,
        userphoto_uri:'http://www.maxlio.com/img/client2.jpg',
        userRating : 3.5,
        likedByCurrentUser:true,
      }
      ]   

  

 export const UserA = {
      id:3,
      userName:'Mustafa.Alghali12',
      email:'mustafa@plantmatch.co',
      password:'12345',
      facebook:'mustafa.alghali',
      google:null,
      instagram:null,
      twitter:'mustafa_alghali',
      website:'www.plantmatch.co',
      photoUri:'http://www.maxlio.com/img/client2.jpg',
      phone:'+249905705498',
      country:'UAE',
      city:'Dubai',
      state:'Dubai',
      postal_code:'00000',
      account_type:'Individual',
      selected_language:'Arabic',
      created:'03-14 00:00:00.000',
      latitude: 37.78825,   
      longitude: -122.4324,
      totalListingsViews: 34,
      rating: 3.5,
      noOfRatings : 3,
      PlantsLikesTotal:21,
      bio:'freelance plant seller works in Seattle area feel free to visit our pages on social media',
      fullAddress:"163b Bahri Industrial street, Dubai, UAE",

 }

 export var ImagesUrls = [ 
           'https://files.genial.guru/files/news/part_15/151455/1488205-calathea_photo_05of36-650x888-650-14397a2d42-1484644360.jpg',
           'http://cdn.home-designing.com/wp-content/uploads/2017/01/indoor-plants-Xerosicyos-danguyi-600x600.jpg',
           'http://cdn.home-designing.com/wp-content/uploads/2017/01/indoor-cactus-Opuntia-microdasys-600x804.jpg'
        ];

